roles/ansible-ldap-kerberos/tasks/install_kerberos_server.yml
=> fix: add dependecy to slapd for kerberos services

roles/ansible-tdp-common-actions/tasks/deploy-ranger-hbase-policy.yml, roles/ansible-tdp-common-actions/tasks/deploy-ranger-hive-policy.yml
Fixes #20 
Add common action to create hbase ranger policies.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.
=> feat: add hbase ranger policy deployment

tdp_vars_defaults/kafka/kafka.yml
=> fix: zk group instead of zk_kafka

roles/kafka/broker/tasks/kerberos.yml, roles/kafka/client/tasks/kerberos.yml, roles/kafka/common/templates/kafka_admin_jaas.conf.j2, roles/livy/server/tasks/kerberos.yml, tdp_vars_defaults/kafka/kafka.yml, tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml, tdp_vars_defaults/zookeeper-kafka/zookeeper-kafka.yml
=> Make principals + keytabs creation optional

roles/livy/server/tasks/install.yml, roles/livy/server/templates/tmpfiles-livy.conf.j2
=> fix(livy): create runtime directory

roles/airflow/templates/airflow-flower.service.j2, roles/airflow/templates/airflow-scheduler.service.j2, roles/airflow/templates/airflow-webserver.service.j2, roles/airflow/templates/airflow-worker.service.j2, roles/kafka/common/templates/kafka-broker.service.j2, roles/livy/server/templates/livy-server.service.j2
=> feat: add systemd services requirements

roles/livy/server/tasks/install.yml
=> fix(livy): name tmpfiles according to service

topology.ini
=> feat: add Ansible inventory file which represent a topology with all services

roles/kafka/broker/tasks/restart.yml, roles/kafka/broker/tasks/start.yml, roles/kafka/broker/tasks/stop.yml, roles/livy/server/tasks/restart.yml, roles/livy/server/tasks/start.yml, roles/livy/server/tasks/stop.yml, tdp_vars_defaults/kafka/kafka.yml, tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml, tdp_vars_defaults/zookeeper-kafka/zookeeper-kafka.yml
=> feat: add "*_start_on_boot" tdp_vars

playbooks/livy-spark3_kerberos_install.yml, playbooks/livy_kerberos_install.yml
=> feat(livy): disable mitogen for unsupported livy playbooks

tdp_vars_defaults/zookeeper-kafka/zookeeper-kafka.yml
=> fix: fix var for zk data dir + add heap props

playbooks/jupyterhub_kerberos_install.yml, playbooks/jupyterhub_server_config.yml, playbooks/jupyterhub_server_hdfs-init.yml, playbooks/jupyterhub_server_init.yml, playbooks/jupyterhub_server_install.yml, playbooks/jupyterhub_server_restart.yml, playbooks/jupyterhub_server_start.yml, playbooks/jupyterhub_server_stop.yml, playbooks/jupyterhub_ssl-tls_install.yml, roles/jupyterhub/README.md, roles/jupyterhub/server/handlers/main.yml, roles/jupyterhub/server/tasks/config.yml, roles/jupyterhub/server/tasks/hdfs-init.yml, roles/jupyterhub/server/tasks/init.yml, roles/jupyterhub/server/tasks/install.yml, roles/jupyterhub/server/tasks/kerberos.yml, roles/jupyterhub/server/tasks/restart.yml, roles/jupyterhub/server/tasks/ssl-tls.yml, roles/jupyterhub/server/tasks/start.yml, roles/jupyterhub/server/tasks/stop.yml, roles/jupyterhub/server/templates/jupyterhub.service.j2, roles/jupyterhub/server/templates/jupyterhub_config.py.j2, roles/jupyterhub/server/templates/jupyterhub_start.sh.j2, tdp_lib_dag/jupyterhub.yml, tdp_vars_defaults/hadoop/hadoop.yml, tdp_vars_defaults/jupyterhub/jupyterhub.yml, tdp_vars_defaults/ranger/ranger_kms.yml, topology.ini
To test this PR, you can find the release at [jupyterhub-pkg#v2.3.1-TDP-0.1.0](https://github.com/TOSIT-IO/jupyterhub-pkg/releases/download/v2.3.1-TDP-0.1.0/jupyterhub-2.3.1-TDP-0.1.0.tar.gz)
Default jupyterhub database is sqlite. In tdp getting-started I will setup postgresql.
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/), you have to acknowledge this by using the following check-box.
=> feat: add jupyterhub implementation

playbooks/jupyterhub_server_hdfs-init.yml, playbooks/zookeeper-kafka_check.yml, playbooks/zookeeper-kafka_client_config.yml, playbooks/zookeeper-kafka_client_install.yml, playbooks/zookeeper-kafka_jmx-exporter_config.yml, playbooks/zookeeper-kafka_kerberos_install.yml, playbooks/zookeeper-kafka_server_check.yml, playbooks/zookeeper-kafka_server_config.yml, playbooks/zookeeper-kafka_server_install.yml, playbooks/zookeeper-kafka_server_restart.yml, playbooks/zookeeper-kafka_server_start.yml, playbooks/zookeeper-kafka_server_stop .yml, tdp_vars_defaults/kafka/kafka.yml, tdp_vars_defaults/zookeeper-kafka/zookeeper-kafka.yml, topology.ini
Fixes #83
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/), you have to acknowledge this by using the following check-box.
=> feat: move service groups into their own groups

playbooks/jupyterhub_server_hdfs-init.yml
=> fix: set jupyterhub hdfs init strategy linear

playbooks/meta/jupyterhub.yml
=> feat: add jupyterhub meta playbook

tdp_vars_defaults/zookeeper-kafka/zookeeper-kafka.yml
=> fix(zookeeper): add required default variables

topology.ini
Section include hue_server
Fixes https://github.com/TOSIT-IO/tdp-collection-prerequisites/issues/67
Additional comments
Relates to PR 
- https://github.com/TOSIT-IO/tdp-collection-prerequisites/pull/68
- https://github.com/TOSIT-IO/tdp-collection/pull/700
=> refactor: add postgresql_client section

tdp_vars_defaults/kafka/kafka.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> refactor(kafka): Set JMX exporter port configurable with default 18202

roles/hue/server/tasks/install.yml, roles/kafka/common/tasks/install.yml, roles/kafka/ranger/tasks/install.yml, roles/livy/server/tasks/install.yml, tdp_vars_defaults/jupyterhub/jupyterhub.yml
=> Variabilize the /tmp path for binaries uploaded files

tdp_vars_defaults/hue/hue.yml
=> fix: postgresql port

.gitignore, roles/hue/server/tasks/install.yml, roles/jupyterhub/server/tasks/install.yml, roles/kafka/common/tasks/install.yml, roles/kafka/ranger/tasks/install.yml, roles/livy/server/tasks/install.yml
=> Add binaries_local_dir variable for local binaries directory

tdp_vars_defaults/hue/hue.yml
=> Hue: add release installation compatible with rocky8

tdp_vars_defaults/zookeeper-kafka/zookeeper-kafka.yml
=> fix: log refactor zookeeper kafka

roles/livy/server/templates/log4j.properties.j2, tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml
=> feat(livy): unify log4j configuration for better log management

tdp_vars_defaults/kafka/kafka.yml
=> fix: name var ranger_kafka_release

roles/hue/server/templates/log.conf.j2, tdp_vars_defaults/hue/hue.yml
=> hue: unify logs configuration for better log management

tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml
=> feat(livy): add knox impersonation support

roles/hue/server/templates/hue.ini.j2
=> hue: fix error when phoenix_queryserver_daemon group not defined

roles/jupyterhub/server/templates/jupyterhub_config.py.j2, tdp_vars_defaults/jupyterhub/jupyterhub.yml
=> feat(jupyterhub): add oauth support

tdp_vars_defaults/kafka/kafka.yml
=> fix: cluster name to use tdp-cluster vars

roles/jupyterhub/server/templates/jupyterhub_config.py.j2, roles/jupyterhub/server/templates/jupyterhub_start.sh.j2, tdp_vars_defaults/jupyterhub/jupyterhub.yml
=> feat(jupyterhub): unify logs configuration for better log management

tdp_vars_defaults/hue/hue.yml, tdp_vars_defaults/jupyterhub/jupyterhub.yml, tdp_vars_defaults/kafka/kafka.yml, tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml, tdp_vars_defaults/zookeeper-kafka/zookeeper-kafka.yml
=> 142 port vars

roles/hue/server/templates/hue.ini.j2, tdp_vars_defaults/hue/hue.yml
Fixes #146 
**Requirements** : 
- HUE 4.11.0 with mozilla-django-oidc==1.0.0
- Python 3.8
This URL should be used for oidc authentication : **https://[your-hue-url]/oidc/authenticate**
=> hue: add OIDC configuration

roles/jupyterhub/server/tasks/config.yml, roles/jupyterhub/server/tasks/install.yml, roles/jupyterhub/server/templates/jupyterhub_config.py.j2, roles/jupyterhub/server/templates/sparkmagic/config.json.j2, tdp_vars_defaults/jupyterhub/jupyterhub.yml
Fixes #150 
**Requirements:**
- use this [jupyterhub-pkg version](https://github.com/TOSIT-IO/jupyterhub-pkg/releases/tag/v2.3.1-TDP-0.1.0-with-oath-sparkmagic) ([branch](https://github.com/TOSIT-IO/jupyterhub-pkg/tree/jupyterhub-sparkmagic))
=> feat(jupyterhub): add sparkmagic kernels

tdp_vars_defaults/jupyterhub/jupyterhub.yml
jupyterhub: add jupyter sessions' persistence on hdfs
=> jupyterhub: add jupyter sessions' persistence on hdfs

tdp_vars_defaults/hue/hue.yml, tdp_vars_defaults/jupyterhub/jupyterhub.yml, tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> refactor: move hue, jupyterhub and livy observability variables to tdp_cluster.yml

tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml
=> livy: enable ACLs for livy for better multi-tenancy

README.md
Fixes none
Following [this discussion](https://github.com/orgs/TOSIT-IO/discussions/92)
=> docs: fix namings and links

tdp_vars_defaults/jupyterhub/jupyterhub.yml
=> jupyterhub: add root_dir for better integration with hdfscm

playbooks/meta/all.yml, playbooks/meta/all_per_service.yml
=> hue: add Hue to update meta playbooks

playbooks/livy-spark3_jmx-exporter_config.yml, playbooks/livy_jmx-exporter_config.yml, playbooks/meta/livy-spark3.yml, playbooks/meta/livy.yml, roles/livy/server/tasks/config.yml, roles/livy/server/tasks/jmx-exporter.yml, roles/livy/server/templates/jmxremote.password.j2, tdp_lib_dag/livy-spark3.yml, tdp_lib_dag/livy.yml, tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> feat: monitor livy & livy-spark3 logs and metrics

tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> feat(livy): observability for livy

roles/jupyterhub/server/templates/jupyterhub_config.py.j2, tdp_vars_defaults/jupyterhub/jupyterhub.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> feat(jupyterhub): normalize jupyterhub logs format

roles/hue/server/tasks/install.yml, roles/hue/server/templates/hue.service.j2, tdp_vars_defaults/hue/hue.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> feat(hue): log format with timezone

tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml
Activate recovery mode for livy
=> feat(livy): activate recovery mode for livy

roles/hue/server/templates/hue.ini.j2, tdp_vars_defaults/hue/hue.yml
This PR removes unused Spark notebooks. They can be reactivated by setting the corresponding variables.
=> feat(hue): remove unused spark notebooks

roles/livy/server/tasks/kerberos.yml, tdp_lib_dag/livy-spark3.yml, tdp_lib_dag/livy.yml, tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml
Following https://github.com/TOSIT-IO/tdp-collection/pull/852, Livy must depends on the new `kerberos_spnego` component.
Moreover, update Livy version to a release one.
=> Livy spnego and update version

roles/hue/server/templates/hue.ini.j2, tdp_vars_defaults/hue/hue.yml
Disable backtrace error on server side for security purpose
=> feat(hue): disable backtrace for server error

tdp_vars_defaults/firewall/firewall.yml
=> feat(firewall): add jupyter hub and livy to firewall

roles/hue/server/tasks/install.yml, roles/kafka/common/tasks/install.yml, roles/kafka/ranger/tasks/install.yml, roles/livy/server/tasks/install.yml
=> fix: ansible.builtin.copy dest should specify full filename

roles/airflow/defaults/main.yaml, tdp_vars_defaults/hue/hue.yml, tdp_vars_defaults/jupyter/jupyter.yml, tdp_vars_defaults/kafka/kafka.yml, tdp_vars_defaults/livy-spark3/livy-spark3.yml, tdp_vars_defaults/livy/livy.yml, tdp_vars_defaults/tdp-cluster/tdp-cluster.yml, tdp_vars_defaults/zookeeper-kafka/zookeeper-kafka.yml
=> feat: Globalize xxx_root_dir default values

tdp_vars_defaults/hue/hue.yml
Fixes None
Changed Hue release version
=> refactor: hue release

tdp_vars_defaults/tdp-cluster/tdp-cluster.yml
=> feat: add unix_group to tdp_observability_target

tdp_vars_defaults/firewall/firewall.yml
Fixes #213
Needs to be sync with https://github.com/TOSIT-IO/tdp-observability/pull/127
=> 213 Firewall fail to deploy if observability is not used
